### ISSUE TITLE
Fix small problem with jQuery require function

### ISSUE THREAD

**Issue by dmuneras** [ip-pauldawson/MoodleDirect#15]
Hi,

A moodle user reported a problem to use Archaius theme with your plugin, I took a look and I found a small detail to fix. You are including jQuery manually where people are using an old Moodle, but in settings.php you are checking if they are in an old Moodle and then you including jquery manually any way.

I made a small fix here: https://gist.github.com/dmuneras/fdaa07c6e3ce610e2e4b
 ...

<?php
/**
 * @package   turnitintool
 * @copyright 2012 Turnitin
 */
defined('MOODLE_INTERNAL') || die;

if ($ADMIN->fulltree) {

    require_once($CFG->dirroot.'/mod/turnitintool/lib.php');
    require_once($CFG->dirroot.'/mod/turnitintool/version.php');

    if (isset($PAGE) AND is_callable(array($PAGE->requires, 'js'))) { // Are we using new moodle or old?
        //$jsurl = new moodle_url($CFG->wwwroot.'/mod/turnitintool/scripts/jquery-1.11.0.min.js');
        //$PAGE->requires->js($jsurl,true);
        //THEY ARE INCLUDING JQUERY MANUALLY EVEN IF IT IS A NEW MOODLE
        $PAGE->requires->jquery();
....

Best regards,
Daniel.

**Comment by jmcgettrick** [comment]
This has now been released in the master branch.
