### ISSUE TITLE
is $cssurl properly defined in index.php?

### ISSUE THREAD

**Issue by arborrow** [ip-pauldawson/MoodleDirect#24]
On one of my production sites, I am seeing:

File does not exist: /var/www/moodle/mod/turnitintool/scripts/styles.css, referer: http://moodle.jesuitcp.org/mod/turnitintool/index.php?id=917

in the apache error log. I checked index.php and noticed that $cssurl is defined as:
$cssurl = new moodle_url($CFG->wwwroot.'/mod/turnitintool/scripts/styles.css');
;however, there is no scripts/styles.css file

should that line instead be:

$cssurl = new moodle_url($CFG->wwwroot.'/mod/turnitintool/styles.css');
as it is in view.php and extras.php

Peace - Anthony

**Comment by jmcgettrick** [comment]
This has now been released in the master branch.
