### ISSUE TITLE
Failure after editing due dates

### ISSUE THREAD

**Issue by rlorenzo** [ip-pauldawson/MoodleDirect#32]
We are running Moodle 2.7.7 and with the latest TurnItIn plugin update our instructors cannot edit due dates. The problem is because the following error occurs:

```
Strict Standards: Non-static method calendar_event::update() should not be called statically in /usr/local/moodle/releases/2.7.7.02-gm/mod/turnitintool/lib.php on line 1367 Fatal error: Using $this when not in object context in /usr/local/moodle/releases/2.7.7.02-gm/calendar/lib.php on line 2227
```

The problem is that the update method isn't being called properly.

**Comment by rlorenzo** [comment]
Added related patch.

**Comment by jmcgettrick** [comment]
Thanks, this has now been released.
