### ISSUE TITLE
Error on file submission using release 2015030301

### ISSUE THREAD

**Issue by EmilyULCC** [ip-pauldawson/MoodleDirect#33]
Hi we are using Moodle 2.8.5 (Build: 20150310) and are experiencing issues for new file submissions, which is preventing us from using the activity. Error below

No file uploaded! Please make sure that you have attached the file that you wish to submit before sending the request. CODE: 1008 (lib.php | 5881)
More information about this error
Debug info: 
Error code: string
Stack trace:
•	line 463 of /lib/setuplib.php: moodle_exception thrown
•	line 7200 of /mod/turnitintool/lib.php: call to print_error()
•	line 7286 of /mod/turnitintool/lib.php: call to turnitintool_print_error()
•	line 28 of /mod/turnitintool/view.php: call to turnitintool_process_api_error()

**Comment by EmilyULCC** [comment]
ah, just found that you have a potential patch in the develop branch https://github.com/ip-pauldawson/MoodleDirect/commit/42fdde58439453cdadc5a33a1a39f16d3f18156a
Can you let us know when this will be added to the master release

**Comment by jmcgettrick** [comment]
This is now in the master branch. Thanks.
