### ISSUE TITLE
Update for Moodle 2.9

### ISSUE THREAD

**Issue by ngmares** [ip-pauldawson/MoodleDirect#38]
Current plugin has a few issues running on the latest version of Moodle.
In particular:
- Reliance on now deprecated upload_manager class in lib.php
- Function turnitintool_add_to_log in lib.php throws an exception when creating a new instance
- Function turnitintool_add_instance in lib.php throws an exception if another module hasn't already loaded the Moodle core calendar/lib.php file because it tries to call add_event which is also deprecated.

The reliance on upload_manager will be the most challenging to fix as this should be rewritten to use the Moodle file management API.

**Comment by jmcgettrick** [comment]
Thanks @ngmares, we are aiming to support 2.9 as soon as possible. I'll leave this issue open until we do.

**Comment by bix0r** [comment]
@jmcgettrick any news on this 2.9 support? Days, weeks, months?

**Comment by jmcgettrick** [comment]
This is now supported in 2.9
