### ISSUE TITLE
API change url (UK)

### ISSUE THREAD

**Issue by svandragt** [ip-pauldawson/MoodleDirect#64]
I was wondering if there is any information regarding the API URL change. In particular, is there a 'must' switchover date which means all installations should be upgraded quickly to this latest version?

**Comment by svandragt** [comment]
FYI
>We are unable to guarantee that the submit.ac.uk URL will continue to function after 31st December 2015.

**Comment by jmcgettrick** [comment]
Hi @svandragt, glad you received the email. Apologies for the delay, but we were waiting for that email to be sent before answering this question.
